defaultEntryPoints = ["http"]
logLevel = "DEBUG"


[entryPoints]
  [entryPoints.http]
  address = ":80"
    [entryPoints.http.redirect]
    entryPoint = "https"
  # [entryPoints.https]
  # address = ":443"
  #   [entryPoints.https.tls]


[web]
address = ":8080"

# [acme]
#
# # Email address used for registration
# #
# # Required
# #
# email = "me@kca.id.au"
# caServer = "https://acme-staging.api.letsencrypt.org/directory"
# storageFile = "/acme.json"
# entryPoint = "https"
[etcd]
endpoint = "10.0.1.227:2379"

watch = true

prefix = "/traefik"
